version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html 
hooks:
  BeforeInstall:
    - location: code/nginx_stop.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: code/print.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: code/start_server.sh
      timeout: 300
      runas: root
